image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup Environment
    command: |
      for file in .vscode/extensions/*.vsix; do
        code --install-extension "$file" || true
      done
      pip install -r requirements.txt

vscode:
  extensions:
    - aaron-bond.better-comments
    - batisteo.vscode-django
    - charliermarsh.ruff
    - christian-kohler.path-intellisense
    - donjayamanne.githistory
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - formulahendry.auto-complete-tag
    - mhutchie.git-graph
    - ms-python.python
    - PKief.material-icon-theme
    - shamanu4.django-intellisense
    - yzhang.markdown-all-in-one
