image:
  file: .gitpod.dockerfile

tasks:
  - name: Start PostgreSQL
    command: |
      /home/gitpod/.pg_ctl/bin/pg_start > /dev/null

  - name: Install Python Dependencies
    command: |
      pip install -r requirements.txt

  - name: Install VS Code Extensions
    command: |
      for file in .vscode/extensions/*.vsix; do
        code --install-extension "$file" || true
      done

vscode:
  extensions:
    - PKief.material-icon-theme
    - charliermarsh.ruff
    - ms-python.python
    - batisteo.vscode-django
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - mhutchie.git-graph
    - donjayamanne.githistory
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - christian-kohler.path-intellisense
    - aaron-bond.better-comments
    - yzhang.markdown-all-in-one
