# DJLint Configuration
# Documentation: https://www.djlint.com/docs/getting-started/

[tool.djlint]
blank_line_after_tag = "load,extends,include,endblock"
blank_line_before_tag = "block,if,for"
close_void_tags = true
format_attribute_template_tags = true
ignore = "H014,H015,H006"
indent = 2
line_break_after_multiline_tag = true
max_attribute_length = 60
max_blank_lines = 0
max_line_length = 100
preserve_blank_lines = true
profile = "django"
use_gitignore = true

[tool.djlint.per-file-ignores]
"templates/base.html" = "H006"

# Ruff Configuration
# Documentation: https://docs.astral.sh/ruff/

[tool.ruff]
exclude = [
    ".direnv",
    ".git",
    ".hg",
    ".nox",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "build",
    "dist",
    "env.py",
    "manage.py",
    "media",
    "migrations",
    "node_modules",
    "site-packages",
    "static",
    "templates",
    "venv",
    "__pycache__",
    "wsgi.py",
    "asgi.py",
]
line-length = 79
indent-width = 4
target-version = "py312"
fix = true
unsafe-fixes = true

[tool.ruff.lint]
select = [
    "C",
    "E",
    "EM",
    "F",
    "DJ",
    "Q",
    "I",
    "UP",
    "W",
    "B",
    "S",
    "RET",
    "SIM",
    "PTH",
    "RUF",
    "ARG",
    "ERA",
    "N",
]

ignore = [
    "Q000",
    "Q001",
    "Q003",
    "E501",
    "B904",
    "DJ001",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"settings.py" = [
    "F401",
    "F403",
    "F405",
    "E501",
]
"tests.py" = [
    "F401",
    "S101",
]
"urls.py" = [
    "E501",
]
"__init__.py" = [
    "F401",
]
"models.py" = [
    "DJ008",
]

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = "dynamic"
